language: node_js
node_js:
  - "node"
  - "14"

before_install:
  - npm i -g npm

install:
  - npm install
  - find dist/ -maxdepth 1 -type f -exec ls -la {} \;
  - find dist/ -maxdepth 1 -type f -exec echo -- {} -- \; -exec head {} \;
  - find dist/ -maxdepth 1 -type f -exec echo -- {} -- \; -exec tail {} \;

script: npm test

cache:
  apt: true
  directories:
  - "$HOME/.npm"
